apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-deployment
  name: hello-world-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30005
  selector:
    app: hello-world-deployment
  type: NodePort
